language: node_js
node_js:
  - "7"
stages:
  - install
  - name: deploy
    if: branch = master
install:
  - npm install
deploy:
  - npm install
  - npm run deploy -- --ftp-username=${FTP_USER} --ftp-pass=${FTP_PASS}
