language: node_js
node_js:
  - "7"
stages:
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: deploy
      script: npm run deploy -- --ftp-username=${FTP_USER} --ftp-pass=${FTP_PASS}
