language: node_js
node_js:
  - "iojs"
  - "7"
deploy:
  - provider: script
    script:
        - npm install
        - npm run deploy -- --ftp-username=${FTP_USER} --ftp-pass=${FTP_PASS}
    on:
      branch: master
