env:
  global:
  - 'SFTP_USER=[sftp-user]'
  - 'SFTP_PASSWORD=[sftp-pass]'
after_success:
- curl --ftp-create-dirs
       -T php
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@wattyrev.com/beta.kitepaint.com/api
